version: '1.0'
services:
  web:
    image: nginx:latest
    ports:
      - "80:80"
    networks:
      - board
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./client/build:/usr/share/nginx/html
    depends_on:
      - mysql
      - api
  api:
    image: node:18-alpine
    networks:
      - board
    ports:
      - "3000:3000"
    volumes:
      - ./server:/app
    command: sh -c "cd /app && npm install && npm start"
    depends_on:
      - mysql
  mysql:
    image: mysql:8.3
    networks:
      - board
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: sql_server
      MYSQL_DATABASE: test_board

    volumes:
      - ./mysql:/var/lib/mysql
    

networks:
  board:
    driver: bridge